name: ANDROID IOT SPEEXDSP DEBUG CI

on:
  push:
    paths-ignore:
      - '**/doc*/**'
      - '**/**/doc*/**'
      - '**/README.md'
      - '**/LICENSE'
      - '*.md'
      - '**/*.md'
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
  IOT_WECOM_CID_ROBOT_KEY: ${{ secrets.IOT_WECOM_CID_ROBOT_KEY }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # - name: Setup NDK
      #   run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
      - name: Update SDK Version
        run: bash .github/scripts/android/update_snapshot_version_code.sh android_speexdsp/build.gradle
      - name: Build and Publish
        run: bash .github/scripts/android/build.sh
      # - name: Report success result to wecom
      #   if: ${{ success() }}
      #   run: |
      #     echo success!!!
      #     bash .github/scripts/android/send_result_to_wecom.sh ${{ github.event.repository.name }} success
      # - name: Report fail result to wecom
      #   if: ${{ failure() }}
      #   run: |
      #     echo fail!!!
      #     bash .github/scripts/android/send_result_to_wecom.sh ${{ github.event.repository.name }} fail
