name: ANDROID IOT SPEEXDSP RELEASE CI

on:
  release:
    types: [published]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}
  IOT_GPG_KEYNAME: ${{ secrets.IOT_GPG_KEYNAME }}
  IOT_GPG_PASSPHRASE: ${{ secrets.IOT_GPG_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/files/secring.gpg.asc > android_speexdsp/secring.gpg
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Update SDK Version
        run: |
          rtt=$(git describe --tags `git rev-list --tags --max-count=1`)
          rt=${rtt#*v}
          sed -i 's#def libVersion.*#def libVersion = \"'$rt'\"#g' android_speexdsp/build.gradle
      - name: Update Values of Signing
        run: |
          export KEY_ID_OF_SIGN=$IOT_GPG_KEYNAME
          export PASSWORD_OF_SIGN=$IOT_GPG_PASSPHRASE
          sh .github/scripts/android/update_values_for_sign.sh
      - name: Build and Publish
        run: bash .github/scripts/android/build.sh